### PR TITLE
Update mime lookup and extension methods for v2

### LINKED ISSUE #30: MIME method updates
I know this hasn't been updated since Nov 2016, but I needed to use it to test something, and it initially did not work because the latest `mime` methods have been renamed. 

I forked this and modified the methods to align:

- `mime.lookup()` -> `mime.getType()`
- `mime.extension()` -> `mime.getExtension()`

If you want a PR for this let me know, otherwise I will close this.

### PR DESCRIPTION
**Pull request by tsnolan23**
- `mime.lookup()` -> `mime.getType()`
- `mime.extension()` -> `mime.getExtension()`

Closes #30

### CODE REVIEW

**Comment by jpmckinney** [comment]
Can you update the minimum version of mime in .travis.yml and in package.json ?

**Comment by tsnolan23** [comment]
@jpmckinney Sorry about that! Fixed

**Comment by jpmckinney** [comment]
Aha, 2.0.0 dropped ES5 support, but 2.0.5 restored it. I've added a commit in #32 to use >= 2.0.5.

**Comment by tsnolan23** [comment]
Ah, good catch

**Comment by jpmckinney** [comment]
Thanks for the PR!

**Pull request merged**
